### ISSUE TITLE
I cant found executable file when go generate

### ISSUE THREAD

**Issue by ghost** [asticode/go-astivid#2]
![not found](https://user-images.githubusercontent.com/20189036/29488854-2b495484-854e-11e7-891a-73db852b0239.png)

what should I do?

**Comment by asticode** [comment]
Mmm this is weird, it seems like `go-bindata` is not installed properly. Could you try one of those 2 following methods and let me know if any worked:

- run `go get -u github.com/asticode/go-astivid/...` and try again `go generate`
- run `go get -u github.com/jteeuwen/go-bindata/...` and try again `go generate`

**Comment by ghost** [comment]
Run `go get -u github.com/jteeuwen/go-bindata/...` before run `go generate` made it a success.
I can run the application.
Thank you so much!
