### ISSUE TITLE
Install the project error

### ISSUE THREAD

**Issue by khigor777** [asticode/go-astivid#4]
I'm trying to install go-astivid, get's an error, jn first step.
note: ffmpeg  installed (7:2.8.11-0ubuntu0.16.04.1).

go get -u github.com/asticode/go-astivid/...
github.com/asticode/go-astitesseract
tesseract.cpp:1:31: fatal error: tesseract/baseapi.h: No such file or directory
compilation terminated.

Any help?

**Comment by asticode** [comment]
@khigor777 should be fixed now, can you confirm?

**Comment by khigor777** [comment]
Thanks, for answer. 
Got another error.
go get github.com/asticode/go-astivid/poc1
package github.com/asticode/go-astivid/poc1: cannot find package "github.com/asticode/go-astivid/poc1

**Comment by asticode** [comment]
yeah this is normal, I've removed this package from the master branch as it's still an unstable work in progress. You shouldn't need to `go get` this package

**Comment by khigor777** [comment]
ok, thanks.
