### ISSUE TITLE
Doesn't currently build

### ISSUE THREAD

**Issue by freman** [asticode/go-astivid#7]
FATA[0007] bundling failed: bundling for environment darwin/amd64 failed: building failed: # github.com/asticode/go-astivid
./main.go:45:3: unknown field 'Homepage' in struct literal of type bootstrap.Options
./main.go:46:3: unknown field 'MessageHandler' in struct literal of type bootstrap.Options
./main.go:48:3: unknown field 'WindowOptions' in struct literal of type bootstrap.Options
: exit status 2

**Comment by asticode** [comment]
Oops indeed.

Should be all good now.

Cheers
